[features]
seeds = false
skip-lint = false
[programs.localnet]
healthcare_dapp = "6o2c3QS8xZYFZ7fjWpfgMtdmDXEJZ9MC2LUpCHjGV2Dn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/bhattacharyakun/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
